"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const admissionController_1 = require("../controllers/admissionController");
const router = (0, express_1.Router)();
router.get('/', admissionController_1.getAllAdmissions);
router.post('/', admissionController_1.createAdmission);
router.put('/:id', admissionController_1.updateAdmission);
router.delete('/:id', admissionController_1.deleteAdmission);
exports.default = router;
